/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CardPanel.java
 *
 * Created on Feb 7, 2011, 12:58:46 PM
 */

package estoquesimples;

import java.awt.CardLayout;

/**
 *
 * @author Renato
 */
public class CardPanel extends javax.swing.JPanel {

    /** Creates new form CardPanel */
    public CardPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaInicial = new javax.swing.JPanel();
        Estoque = new javax.swing.JButton();
        label1 = new java.awt.Label();
        Cliente = new javax.swing.JButton();
        Fornecedor = new javax.swing.JButton();
        Financeiro = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        telaEstoque = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        telaInsereEstoque = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        novoCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        telaInicial.setBackground(new java.awt.Color(51, 153, 255));
        telaInicial.setForeground(new java.awt.Color(153, 0, 204));
        telaInicial.setName("telaInicial"); // NOI18N
        telaInicial.setPreferredSize(new java.awt.Dimension(800, 600));

        Estoque.setText("Estoque");
        Estoque.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Estoque.setName("Estoque"); // NOI18N
        Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstoqueActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 51));
        label1.setName("labelNomePrograma"); // NOI18N
        label1.setText("Estoque Simples");

        Cliente.setText("Cliente");
        Cliente.setName("Cliente"); // NOI18N

        Fornecedor.setText("Fornecedor");
        Fornecedor.setName("Fornecedor"); // NOI18N

        Financeiro.setText("Fianceiro");
        Financeiro.setName("Financeiro"); // NOI18N

        Sair.setText("Sair");
        Sair.setName("Sair"); // NOI18N
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaInicialLayout = new javax.swing.GroupLayout(telaInicial);
        telaInicial.setLayout(telaInicialLayout);
        telaInicialLayout.setHorizontalGroup(
            telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Financeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(telaInicialLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
            .addGroup(telaInicialLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        telaInicialLayout.setVerticalGroup(
            telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(telaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Financeiro, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        add(telaInicial, "cardInicial");

        telaEstoque.setName("telaEstoque"); // NOI18N

        jButton5.setText("Novo Item");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Editar Item");
        jButton6.setName("jButton6"); // NOI18N

        jButton7.setText("Remover Item");
        jButton7.setName("jButton7"); // NOI18N

        jButton8.setText("Listar Estoque");
        jButton8.setName("jButton8"); // NOI18N

        jButton9.setText("Voltar");
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Gerencia Estoque");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout telaEstoqueLayout = new javax.swing.GroupLayout(telaEstoque);
        telaEstoque.setLayout(telaEstoqueLayout);
        telaEstoqueLayout.setHorizontalGroup(
            telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaEstoqueLayout.createSequentialGroup()
                .addGroup(telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaEstoqueLayout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel2))
                    .addGroup(telaEstoqueLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9)
                            .addGroup(telaEstoqueLayout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addGap(31, 31, 31)
                                .addComponent(jButton7)
                                .addGap(35, 35, 35)
                                .addComponent(jButton8)))))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        telaEstoqueLayout.setVerticalGroup(
            telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(76, 76, 76)
                .addComponent(jButton9)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        add(telaEstoque, "cardEstoque");

        telaInsereEstoque.setName("telaInsereEstoque"); // NOI18N

        label2.setFont(new java.awt.Font("Dialog", 1, 14));
        label2.setName("tituloInsereEstoque"); // NOI18N
        label2.setText("Incluir Novo Produto");

        novoCodigo.setName("novoCodigo"); // NOI18N

        jLabel1.setText("Código:");
        jLabel1.setName("jLabel1"); // NOI18N

        jButton10.setText("Voltar");
        jButton10.setName("jButton10"); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaInsereEstoqueLayout = new javax.swing.GroupLayout(telaInsereEstoque);
        telaInsereEstoque.setLayout(telaInsereEstoqueLayout);
        telaInsereEstoqueLayout.setHorizontalGroup(
            telaInsereEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInsereEstoqueLayout.createSequentialGroup()
                .addGroup(telaInsereEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaInsereEstoqueLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaInsereEstoqueLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(novoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaInsereEstoqueLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton10)))
                .addContainerGap(622, Short.MAX_VALUE))
        );
        telaInsereEstoqueLayout.setVerticalGroup(
            telaInsereEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInsereEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(telaInsereEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(novoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addComponent(jButton10)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        add(telaInsereEstoque, "cardInsereEstoque");
    }// </editor-fold>//GEN-END:initComponents

    private void EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstoqueActionPerformed
        CardLayout cl = (CardLayout) (this.getLayout());
        cl.show(this, "cardEstoque");
    }//GEN-LAST:event_EstoqueActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        CardLayout cl = (CardLayout) (this.getLayout());
        cl.show(this, "cardInicial");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout cl = (CardLayout) (this.getLayout());
        cl.show(this, "cardInsereEstoque");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        CardLayout cl = (CardLayout) (this.getLayout());
        cl.show(this, "cardEstoque");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cliente;
    private javax.swing.JButton Estoque;
    private javax.swing.JButton Financeiro;
    private javax.swing.JButton Fornecedor;
    private javax.swing.JButton Sair;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField novoCodigo;
    private javax.swing.JPanel telaEstoque;
    private javax.swing.JPanel telaInicial;
    private javax.swing.JPanel telaInsereEstoque;
    // End of variables declaration//GEN-END:variables

}
